apiVersion: v1
kind: Service
metadata:
  name: {{ include "eaas-backend-conventer-swagger.fullname" . }}
  labels:
    {{- include "eaas-backend-conventer-swagger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "eaas-backend-conventer-swagger.selectorLabels" . | nindent 4 }}
