name: CI for EaaS Backend Conventer Swagger Application

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "automation/**"

jobs:   
  build:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      tag: ${{ steps.image_tag.outputs.tag }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-session-name: eaas-backend-conventer-swagger-app
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package --file pom.xml -DskipTests

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
  
    - name: Generate image tag by sha
      id: image_tag
      run: |
        tag="${GITHUB_SHA::7}"
        echo tag=$tag >> $GITHUB_OUTPUT

    - name: Build and push to ECR
      run: |
        image_tag="${GITHUB_SHA::7}"
        docker buildx build \
          --file ./Dockerfile \
          --tag ${{ secrets.ECR_REPOSITORY_URL }}:${{ steps.image_tag.outputs.tag }} \
          --no-cache \
          --push .
