name: Swagger Parser Dependency Update
on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      version:
        description: 'Version to update to'
        required: true
jobs:
  update-swagger-parser-dependency:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set up Python 2.7
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: 2.7
      - name: update-dependency
        run: |
          mvn versions:set-property -DnewVersion=${{ inputs.version }} -Dproperty=swagger-parser-version
      - name: Create PR for new dependency version
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: updating swagger-parser dependency to version ${{ inputs.version }}
          title: 'update-swagger-parser-to-${{ inputs.version }}'
          branch: update-swagger-parser-to-${{ inputs.version }}
          delete-branch: true
      - name: Merge new branch into master
        run: |
          git checkout master
          git merge update-swagger-parser-to-${{ inputs.version }}
          git push
      - name: release
        run: |
          if [[ ${{ inputs.version }} =~ ^.*SNAPSHOT$ ]];
          then
            echo "RELEASE_OK=no" >> $GITHUB_ENV
          else
            CURRENT_VERSION=$(CI/version.sh)
            RELEASE_VERSION=${CURRENT_VERSION/-SNAPSHOT/}
            mvn -q versions:set -DnewVersion="${RELEASE_VERSION}"
            echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
            echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
            echo "RELEASE_OK=yes" >> $GITHUB_ENV
          fi
      - name: Create PR for new release
        uses: peter-evans/create-pull-request@v4
        if: env.RELEASE_OK == 'yes'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: updating swagger-parser dependency to version ${{ inputs.version }}
          title: 'release-to-${{ env.RELEASE_VERSION }}'
          branch: release-to-${{ env.RELEASE_VERSION }}
          delete-branch: true

      - name: Merge release changes branch into master
        if: env.RELEASE_OK == 'yes'
        run: |
          git checkout master
          git merge release-to-${{ env.RELEASE_VERSION }}
          git push

      - name: bump up to next snapshot
        if: env.RELEASE_OK == 'yes'
        shell: bash
        run: |
          pwd
          sh CI/bump-version.sh
          BUMPED_VERSION=$(CI/version.sh)
          echo "BUMPED_VERSION=$BUMPED_VERSION" >> $GITHUB_ENV
      - name: Create PR for next snapshot
        uses: peter-evans/create-pull-request@v4
        if: env.RELEASE_OK == 'yes'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "bump to next snapshot: ${{ env.BUMPED_VERSION }}"
          title: 'next-version-to-${{ env.BUMPED_VERSION }}'
          branch: next-version-to-${{ env.BUMPED_VERSION }}
          delete-branch: true
      - name: Merge next version bumping changes into master
        if: env.RELEASE_OK == 'yes'
        run: |
          git checkout master
          git merge next-version-to-${{ env.BUMPED_VERSION }}
          git push    
